/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MediaType = IDL.Variant({
  'audio' : IDL.Null,
  'other' : IDL.Text,
  'video' : IDL.Null,
  'document' : IDL.Null,
  'image' : IDL.Null,
});
export const StatusContent = IDL.Record({
  'text' : IDL.Text,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'mediaType' : IDL.Opt(MediaType),
});
export const StatusId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const ConversationId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'lastSeen' : Timestamp,
});
export const Status = IDL.Record({
  'id' : StatusId,
  'content' : StatusContent,
  'author' : UserId,
  'timestamp' : Timestamp,
});
export const MessageId = IDL.Nat;
export const MessageContent = IDL.Record({
  'text' : IDL.Text,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'mediaType' : IDL.Opt(MediaType),
});
export const MessageReadReceipt = IDL.Record({
  'userId' : UserId,
  'timestamp' : Timestamp,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : MessageContent,
  'readReceipts' : IDL.Vec(MessageReadReceipt),
  'sender' : UserId,
  'timestamp' : Timestamp,
});
export const ConversationType = IDL.Variant({
  'group' : IDL.Text,
  'direct' : IDL.Null,
});
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'lastMessageTimestamp' : IDL.Int,
  'members' : IDL.Vec(UserId),
  'messages' : IDL.Vec(Message),
  'type' : ConversationType,
});
export const MessageInput = IDL.Record({ 'content' : MessageContent });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStatus' : IDL.Func([StatusContent], [StatusId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDirectConversation' : IDL.Func([UserId], [ConversationId], []),
  'createGroupConversation' : IDL.Func(
      [IDL.Text, IDL.Vec(UserId)],
      [ConversationId],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactStatuses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserProfile, IDL.Vec(Status)))],
      ['query'],
    ),
  'getConversation' : IDL.Func(
      [ConversationId],
      [IDL.Opt(Conversation)],
      ['query'],
    ),
  'getMessageReadReceipts' : IDL.Func(
      [ConversationId, MessageId],
      [IDL.Opt(IDL.Vec(MessageReadReceipt))],
      ['query'],
    ),
  'getMyStatuses' : IDL.Func([], [IDL.Vec(Status)], ['query']),
  'getPaginatedMessages' : IDL.Func(
      [ConversationId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserOnline' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'listUserConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'markMessagesAsRead' : IDL.Func([ConversationId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUserByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Record({ 'userId' : UserId, 'profile' : UserProfile }))],
      [],
    ),
  'sendMessage' : IDL.Func([ConversationId, MessageInput], [MessageId], []),
  'updateCallerAvatar' : IDL.Func([IDL.Text], [], []),
  'updateCallerBio' : IDL.Func([IDL.Text], [], []),
  'updateCallerDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateLastSeen' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MediaType = IDL.Variant({
    'audio' : IDL.Null,
    'other' : IDL.Text,
    'video' : IDL.Null,
    'document' : IDL.Null,
    'image' : IDL.Null,
  });
  const StatusContent = IDL.Record({
    'text' : IDL.Text,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'mediaType' : IDL.Opt(MediaType),
  });
  const StatusId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const ConversationId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'lastSeen' : Timestamp,
  });
  const Status = IDL.Record({
    'id' : StatusId,
    'content' : StatusContent,
    'author' : UserId,
    'timestamp' : Timestamp,
  });
  const MessageId = IDL.Nat;
  const MessageContent = IDL.Record({
    'text' : IDL.Text,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'mediaType' : IDL.Opt(MediaType),
  });
  const MessageReadReceipt = IDL.Record({
    'userId' : UserId,
    'timestamp' : Timestamp,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : MessageContent,
    'readReceipts' : IDL.Vec(MessageReadReceipt),
    'sender' : UserId,
    'timestamp' : Timestamp,
  });
  const ConversationType = IDL.Variant({
    'group' : IDL.Text,
    'direct' : IDL.Null,
  });
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'lastMessageTimestamp' : IDL.Int,
    'members' : IDL.Vec(UserId),
    'messages' : IDL.Vec(Message),
    'type' : ConversationType,
  });
  const MessageInput = IDL.Record({ 'content' : MessageContent });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStatus' : IDL.Func([StatusContent], [StatusId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDirectConversation' : IDL.Func([UserId], [ConversationId], []),
    'createGroupConversation' : IDL.Func(
        [IDL.Text, IDL.Vec(UserId)],
        [ConversationId],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactStatuses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserProfile, IDL.Vec(Status)))],
        ['query'],
      ),
    'getConversation' : IDL.Func(
        [ConversationId],
        [IDL.Opt(Conversation)],
        ['query'],
      ),
    'getMessageReadReceipts' : IDL.Func(
        [ConversationId, MessageId],
        [IDL.Opt(IDL.Vec(MessageReadReceipt))],
        ['query'],
      ),
    'getMyStatuses' : IDL.Func([], [IDL.Vec(Status)], ['query']),
    'getPaginatedMessages' : IDL.Func(
        [ConversationId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserOnline' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'listUserConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'markMessagesAsRead' : IDL.Func([ConversationId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUserByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Record({ 'userId' : UserId, 'profile' : UserProfile }))],
        [],
      ),
    'sendMessage' : IDL.Func([ConversationId, MessageInput], [MessageId], []),
    'updateCallerAvatar' : IDL.Func([IDL.Text], [], []),
    'updateCallerBio' : IDL.Func([IDL.Text], [], []),
    'updateCallerDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateCallerDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateLastSeen' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };