/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsResult {
  'activeUsers' : bigint,
  'channelsCreated' : bigint,
  'totalMessages' : bigint,
  'totalGoldVolume' : number,
  'storiesPosted' : bigint,
  'totalUsers' : bigint,
}
export interface AppNotification {
  'id' : NotificationId,
  'kind' : NotificationKind,
  'read' : boolean,
  'timestamp' : Timestamp,
}
export interface Channel {
  'id' : ChannelId,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'avatarUrl' : [] | [string],
}
export type ChannelCommentId = bigint;
export interface ChannelCommentWithProfile {
  'id' : ChannelCommentId,
  'text' : string,
  'author' : UserProfile,
  'timestamp' : Timestamp,
}
export type ChannelId = bigint;
export interface ChannelPost {
  'id' : ChannelPostId,
  'content' : ChannelPostContent,
  'channelId' : ChannelId,
  'author' : UserId,
  'timestamp' : Timestamp,
}
export interface ChannelPostContent {
  'text' : string,
  'mediaUrl' : [] | [string],
  'mediaType' : [] | [MediaType],
}
export type ChannelPostId = bigint;
export interface ChannelPostInteractions {
  'likeCount' : bigint,
  'comments' : Array<ChannelCommentWithProfile>,
  'likedByMe' : boolean,
}
export interface ChannelWithMeta {
  'ownerProfile' : UserProfile,
  'isFollowing' : boolean,
  'followerCount' : bigint,
  'channel' : Channel,
}
export type CommentId = bigint;
export interface Conversation {
  'id' : ConversationId,
  'lastMessageTimestamp' : bigint,
  'members' : Array<UserId>,
  'messages' : Array<Message>,
  'type' : ConversationType,
}
export type ConversationId = bigint;
export type ConversationType = { 'group' : string } |
  { 'direct' : null };
export interface DealerInfo {
  'username' : string,
  'balance' : bigint,
  'avatarUrl' : [] | [string],
}
export interface GoldTransaction {
  'id' : GoldTxId,
  'timestamp' : Timestamp,
  'txType' : GoldTxType,
  'counterpartyUsername' : [] | [string],
  'amount' : bigint,
}
export type GoldTxId = bigint;
export type GoldTxType = { 'buyRequest' : null } |
  { 'sent' : null } |
  { 'claimed' : null } |
  { 'received' : null } |
  { 'sellRequest' : null };
export type MediaType = { 'audio' : null } |
  { 'other' : string } |
  { 'video' : null } |
  { 'document' : null } |
  { 'image' : null };
export interface Message {
  'id' : MessageId,
  'content' : MessageContent,
  'readReceipts' : Array<MessageReadReceipt>,
  'sender' : UserId,
  'timestamp' : Timestamp,
}
export interface MessageContent {
  'text' : string,
  'mediaUrl' : [] | [string],
  'mediaType' : [] | [MediaType],
}
export type MessageId = bigint;
export interface MessageInput { 'content' : MessageContent }
export interface MessageReadReceipt {
  'userId' : UserId,
  'timestamp' : Timestamp,
}
export type NotificationId = bigint;
export type NotificationKind = {
    'goldGifted' : { 'fromUsername' : string, 'amount' : bigint }
  } |
  {
    'channelPostLiked' : {
      'channelId' : bigint,
      'byUsername' : string,
      'postId' : bigint,
    }
  } |
  {
    'channelPostCommented' : {
      'channelId' : bigint,
      'byUsername' : string,
      'postId' : bigint,
    }
  } |
  { 'storyCommented' : { 'byUsername' : string, 'statusId' : bigint } } |
  { 'storyLiked' : { 'byUsername' : string, 'statusId' : bigint } } |
  { 'channelFollowed' : { 'channelId' : bigint, 'byUsername' : string } };
export interface Status {
  'id' : StatusId,
  'content' : StatusContent,
  'author' : UserId,
  'timestamp' : Timestamp,
}
export interface StatusCommentWithProfile {
  'id' : CommentId,
  'text' : string,
  'author' : UserProfile,
  'timestamp' : Timestamp,
}
export interface StatusContent {
  'text' : string,
  'mediaUrl' : [] | [string],
  'mediaType' : [] | [MediaType],
}
export type StatusId = bigint;
export interface StatusInteractions {
  'likeCount' : bigint,
  'comments' : Array<StatusCommentWithProfile>,
  'likedByMe' : boolean,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'bio' : [] | [string],
  'username' : string,
  'displayName' : string,
  'avatarUrl' : [] | [string],
  'lastSeen' : Timestamp,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addChannelPost' : ActorMethod<
    [ChannelId, ChannelPostContent],
    ChannelPostId
  >,
  'addGroupMember' : ActorMethod<[ConversationId, string], undefined>,
  'addStatus' : ActorMethod<[StatusContent], StatusId>,
  'adminClaimGold' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[UserId], undefined>,
  'bookmarkPost' : ActorMethod<
    [ChannelPostId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'commentOnChannelPost' : ActorMethod<
    [ChannelPostId, string],
    ChannelCommentId
  >,
  'commentOnStatus' : ActorMethod<[StatusId, string], CommentId>,
  'createChannel' : ActorMethod<[string, string, [] | [string]], ChannelId>,
  'createDirectConversation' : ActorMethod<[UserId], ConversationId>,
  'createGroupConversation' : ActorMethod<
    [string, Array<UserId>, [] | [string]],
    ConversationId
  >,
  'deleteChannel' : ActorMethod<[ChannelId], undefined>,
  'deleteChannelPost' : ActorMethod<[ChannelPostId], undefined>,
  'deleteGroupName' : ActorMethod<[ConversationId], undefined>,
  'deleteMessage' : ActorMethod<[ConversationId, MessageId], undefined>,
  'editChannelPost' : ActorMethod<
    [ChannelPostId, ChannelPostContent],
    undefined
  >,
  'editMessage' : ActorMethod<[ConversationId, MessageId, string], undefined>,
  'followChannel' : ActorMethod<[ChannelId], undefined>,
  'forwardChannelPost' : ActorMethod<
    [ChannelPostId, ConversationId],
    MessageId
  >,
  'getAdminTotalClaimed' : ActorMethod<[], bigint>,
  'getAllChannels' : ActorMethod<[], Array<ChannelWithMeta>>,
  'getAllStories' : ActorMethod<[], Array<[UserProfile, Array<Status>]>>,
  'getAnalytics' : ActorMethod<[], AnalyticsResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannel' : ActorMethod<[ChannelId], [] | [ChannelWithMeta]>,
  'getChannelPostInteractions' : ActorMethod<
    [ChannelPostId],
    ChannelPostInteractions
  >,
  'getChannelPostViewCount' : ActorMethod<[ChannelPostId], bigint>,
  'getChannelPosts' : ActorMethod<[ChannelId], Array<ChannelPost>>,
  'getContactStatuses' : ActorMethod<[], Array<[UserProfile, Array<Status>]>>,
  'getConversation' : ActorMethod<[ConversationId], [] | [Conversation]>,
  'getGroupAvatars' : ActorMethod<[], Array<[ConversationId, string]>>,
  'getGroupCreators' : ActorMethod<[], Array<[ConversationId, UserId]>>,
  'getHighlightedStatuses' : ActorMethod<[UserId], Array<Status>>,
  'getMessageReadReceipts' : ActorMethod<
    [ConversationId, MessageId],
    [] | [Array<MessageReadReceipt>]
  >,
  'getMessages' : ActorMethod<[ConversationId, bigint, bigint], Array<Message>>,
  'getMyBlockedUsers' : ActorMethod<[], Array<UserProfile>>,
  'getMyBookmarkedPosts' : ActorMethod<[], Array<ChannelPost>>,
  'getMyConversations' : ActorMethod<[], Array<Conversation>>,
  'getMyGoldBalance' : ActorMethod<[], bigint>,
  'getMyGoldTransactions' : ActorMethod<[], Array<GoldTransaction>>,
  'getMyHighlights' : ActorMethod<[], Array<StatusId>>,
  'getMyNotifications' : ActorMethod<[], Array<AppNotification>>,
  'getMyStatuses' : ActorMethod<[], Array<Status>>,
  'getMyTransactionHistory' : ActorMethod<[], Array<GoldTransaction>>,
  'getPaginatedMessages' : ActorMethod<
    [ConversationId, bigint, bigint],
    Array<Message>
  >,
  'getStatusInteractions' : ActorMethod<[StatusId], StatusInteractions>,
  'getStatusViewCount' : ActorMethod<[StatusId], bigint>,
  'getUnreadCount' : ActorMethod<[ConversationId], bigint>,
  'getUserByPrincipal' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserHighlights' : ActorMethod<[UserId], Array<StatusId>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUsersWithGoldAbove' : ActorMethod<[bigint], Array<DealerInfo>>,
  'isBlockedBy' : ActorMethod<[UserId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserOnline' : ActorMethod<[UserId], boolean>,
  'leaveConversation' : ActorMethod<[ConversationId], undefined>,
  'likeChannelPost' : ActorMethod<[ChannelPostId], undefined>,
  'likeStatus' : ActorMethod<[StatusId], undefined>,
  'listUserConversations' : ActorMethod<[], Array<Conversation>>,
  'markAsRead' : ActorMethod<[ConversationId], undefined>,
  'markMessagesAsRead' : ActorMethod<[ConversationId], undefined>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'recordChannelPostView' : ActorMethod<[ChannelPostId], undefined>,
  'recordStatusView' : ActorMethod<[StatusId], undefined>,
  'removeGroupMember' : ActorMethod<[ConversationId, UserId], undefined>,
  'removeHighlight' : ActorMethod<
    [StatusId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'requestBuyGold' : ActorMethod<[bigint], undefined>,
  'requestSellGold' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveHighlight' : ActorMethod<
    [StatusId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'searchUserByUsername' : ActorMethod<
    [string],
    [] | [{ 'userId' : UserId, 'profile' : UserProfile }]
  >,
  'searchUsers' : ActorMethod<
    [string],
    Array<{ 'userId' : UserId, 'profile' : UserProfile }>
  >,
  'sendMessage' : ActorMethod<[ConversationId, MessageInput], MessageId>,
  'transferGold' : ActorMethod<[string, bigint], undefined>,
  'unblockUser' : ActorMethod<[UserId], undefined>,
  'unbookmarkPost' : ActorMethod<
    [ChannelPostId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'unfollowChannel' : ActorMethod<[ChannelId], undefined>,
  'unlikeChannelPost' : ActorMethod<[ChannelPostId], undefined>,
  'unlikeStatus' : ActorMethod<[StatusId], undefined>,
  'updateCallerAvatar' : ActorMethod<[string], undefined>,
  'updateCallerBio' : ActorMethod<[string], undefined>,
  'updateCallerDisplayName' : ActorMethod<[string], undefined>,
  'updateChannel' : ActorMethod<
    [ChannelId, string, string, [] | [string]],
    undefined
  >,
  'updateGroupAvatar' : ActorMethod<[ConversationId, string], undefined>,
  'updateGroupName' : ActorMethod<[ConversationId, string], undefined>,
  'updateLastSeen' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];