/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Conversation {
  'id' : ConversationId,
  'lastMessageTimestamp' : bigint,
  'members' : Array<UserId>,
  'messages' : Array<Message>,
  'type' : ConversationType,
}
export type ConversationId = bigint;
export type ConversationType = { 'group' : string } |
  { 'direct' : null };
export type MediaType = { 'audio' : null } |
  { 'other' : string } |
  { 'video' : null } |
  { 'document' : null } |
  { 'image' : null };
export interface Message {
  'id' : MessageId,
  'content' : MessageContent,
  'readReceipts' : Array<MessageReadReceipt>,
  'sender' : UserId,
  'timestamp' : Timestamp,
}
export interface MessageContent {
  'text' : string,
  'mediaUrl' : [] | [string],
  'mediaType' : [] | [MediaType],
}
export type MessageId = bigint;
export interface MessageInput { 'content' : MessageContent }
export interface MessageReadReceipt {
  'userId' : UserId,
  'timestamp' : Timestamp,
}
export interface Status {
  'id' : StatusId,
  'content' : StatusContent,
  'author' : UserId,
  'timestamp' : Timestamp,
}
export interface StatusContent {
  'text' : string,
  'mediaUrl' : [] | [string],
  'mediaType' : [] | [MediaType],
}
export type StatusId = bigint;
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'bio' : [] | [string],
  'username' : string,
  'displayName' : string,
  'avatarUrl' : [] | [string],
  'lastSeen' : Timestamp,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStatus' : ActorMethod<[StatusContent], StatusId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDirectConversation' : ActorMethod<[UserId], ConversationId>,
  'createGroupConversation' : ActorMethod<
    [string, Array<UserId>],
    ConversationId
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactStatuses' : ActorMethod<[], Array<[UserProfile, Array<Status>]>>,
  'getConversation' : ActorMethod<[ConversationId], [] | [Conversation]>,
  'getMessageReadReceipts' : ActorMethod<
    [ConversationId, MessageId],
    [] | [Array<MessageReadReceipt>]
  >,
  'getMyStatuses' : ActorMethod<[], Array<Status>>,
  'getPaginatedMessages' : ActorMethod<
    [ConversationId, bigint, bigint],
    Array<Message>
  >,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserOnline' : ActorMethod<[UserId], boolean>,
  'listUserConversations' : ActorMethod<[], Array<Conversation>>,
  'markMessagesAsRead' : ActorMethod<[ConversationId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUserByUsername' : ActorMethod<
    [string],
    [] | [{ 'userId' : UserId, 'profile' : UserProfile }]
  >,
  'sendMessage' : ActorMethod<[ConversationId, MessageInput], MessageId>,
  'updateCallerAvatar' : ActorMethod<[string], undefined>,
  'updateCallerBio' : ActorMethod<[string], undefined>,
  'updateCallerDisplayName' : ActorMethod<[string], undefined>,
  'updateLastSeen' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];